# Generated by Django 4.2.3 on 2023-12-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
