# Generated by Django 4.2.2 on 2023-09-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='account_number',
        ),
    ]
