# Generated by Django 4.2.2 on 2023-09-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
